/**
 * Static boss fight definitions.
 * Each boss corresponds to a real national BAC exam from our scraped dataset.
 * Requirements are tuned so students must complete curriculum quests first.
 */

import type { BossFight } from "@/types/boss";

export const BOSS_FIGHTS: BossFight[] = [
  // ── 2024 National Exams ───────────────────────────────────────────────────
  {
    id: "national-2024-phys-sm",
    title: "Examen National 2024 – Sciences Physiques SM",
    titleAr: "الامتحان الوطني 2024 – العلوم الفيزيائية SM",
    examYear: 2024,
    subject: "physique-chimie",
    filiere: "sm",
    level: "2bac",
    passThreshold: 14,
    totalPoints: 20,
    difficulty: 5,
    flavor: "The final boss awaits. 2024's national exam — the one that separated the legends from the rest.",
    flavorAr: "الامتحان الوطني 2024 — الاختبار الذي ميّز الأساطير عن البقية.",
    bgGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    iconEmoji: "⚡",
    topics: ["électrostatique", "mécanique", "ondes", "noyau atomique", "oxydoréduction"],
    requirements: [
      { type: "quests_completed", value: 10, label: "Compléter 10 quizzes" },
      { type: "xp_threshold", value: 500, label: "Atteindre 500 XP" },
      { type: "lessons_read", value: 8, label: "Lire 8 cours" },
    ],
    rewards: [
      {
        type: "profile_frame",
        id: "frame-national-2024-sm",
        label: "Cadre « Survivant 2024 SM »",
        labelAr: "إطار «ناجح 2024 SM»",
        cssClass: "frame-gold-glow",
      },
      {
        type: "baccoins",
        id: "coins-boss-2024-sm",
        label: "+100 BacCoins",
        labelAr: "+100 باك كوين",
      },
      {
        type: "badge",
        id: "badge-national-2024-sm",
        label: "Badge National 2024 SM",
        labelAr: "شارة الوطني 2024 SM",
      },
    ],
    examPdfUrl: undefined,
    correctionPdfUrl: undefined,
  },
  {
    id: "national-2024-phys-sp",
    title: "Examen National 2024 – Sciences Physiques SP",
    titleAr: "الامتحان الوطني 2024 – العلوم الفيزيائية SP",
    examYear: 2024,
    subject: "physique-chimie",
    filiere: "sp",
    level: "2bac",
    passThreshold: 14,
    totalPoints: 20,
    difficulty: 5,
    flavor: "SP students face their dragon. The 2024 national: 3 hours of pure pressure.",
    flavorAr: "طلاب SP يواجهون تنينهم — 3 ساعات من الضغط الحقيقي.",
    bgGradient: "linear-gradient(135deg, #0d0221 0%, #190a32 50%, #371a6e 100%)",
    iconEmoji: "🧪",
    topics: ["réactions chimiques", "mécanique", "électricité", "ondes"],
    requirements: [
      { type: "quests_completed", value: 10, label: "Compléter 10 quizzes" },
      { type: "xp_threshold", value: 500, label: "Atteindre 500 XP" },
      { type: "lessons_read", value: 8, label: "Lire 8 cours" },
    ],
    rewards: [
      {
        type: "profile_frame",
        id: "frame-national-2024-sp",
        label: "Cadre « Survivant 2024 SP »",
        labelAr: "إطار «ناجح 2024 SP»",
        cssClass: "frame-purple-glow",
      },
      { type: "baccoins", id: "coins-boss-2024-sp", label: "+100 BacCoins", labelAr: "+100 باك كوين" },
    ],
    examPdfUrl: undefined,
    correctionPdfUrl: undefined,
  },
  {
    id: "national-2024-math-sm",
    title: "Examen National 2024 – Mathématiques SM",
    titleAr: "الامتحان الوطني 2024 – الرياضيات SM",
    examYear: 2024,
    subject: "maths",
    filiere: "sm",
    level: "2bac",
    passThreshold: 14,
    totalPoints: 20,
    difficulty: 5,
    flavor: "Analysis, algebra, and probability. The 2024 maths boss doesn't forgive mistakes.",
    flavorAr: "التحليل، الجبر، والاحتمالات. نهائي الرياضيات 2024 لا يغفر الأخطاء.",
    bgGradient: "linear-gradient(135deg, #0a1628 0%, #0f2042 50%, #1a3a6e 100%)",
    iconEmoji: "∑",
    topics: ["analyse", "algèbre", "probabilités", "géométrie", "nombres complexes"],
    requirements: [
      { type: "quests_completed", value: 12, label: "Compléter 12 quizzes" },
      { type: "xp_threshold", value: 600, label: "Atteindre 600 XP" },
      { type: "lessons_read", value: 10, label: "Lire 10 cours" },
    ],
    rewards: [
      {
        type: "profile_frame",
        id: "frame-national-2024-math",
        label: "Cadre « Mathématicien 2024 »",
        labelAr: "إطار «رياضياتي 2024»",
        cssClass: "frame-blue-glow",
      },
      { type: "baccoins", id: "coins-boss-2024-math", label: "+100 BacCoins", labelAr: "+100 باك كوين" },
    ],
    examPdfUrl: undefined,
    correctionPdfUrl: undefined,
  },

  // ── 2023 National Exams ───────────────────────────────────────────────────
  {
    id: "national-2023-phys-sm",
    title: "Examen National 2023 – Sciences Physiques SM",
    titleAr: "الامتحان الوطني 2023 – العلوم الفيزيائية SM",
    examYear: 2023,
    subject: "physique-chimie",
    filiere: "sm",
    level: "2bac",
    passThreshold: 14,
    totalPoints: 20,
    difficulty: 5,
    flavor: "Last year's legend. Master the past to conquer the future.",
    flavorAr: "أسطورة العام الماضي. افهم الماضي لتسيطر على المستقبل.",
    bgGradient: "linear-gradient(135deg, #1a0a2e 0%, #2d1b69 50%, #11998e 100%)",
    iconEmoji: "🔮",
    topics: ["électrostatique", "optique", "thermodynamique", "chimie organique"],
    requirements: [
      { type: "quests_completed", value: 8, label: "Compléter 8 quizzes" },
      { type: "xp_threshold", value: 400, label: "Atteindre 400 XP" },
    ],
    rewards: [
      {
        type: "profile_frame",
        id: "frame-national-2023-sm",
        label: "Cadre « Classe 2023 SM »",
        labelAr: "إطار «دفعة 2023 SM»",
        cssClass: "frame-teal-glow",
      },
      { type: "baccoins", id: "coins-boss-2023-sm", label: "+80 BacCoins", labelAr: "+80 باك كوين" },
    ],
    examPdfUrl: undefined,
    correctionPdfUrl: undefined,
  },
  {
    id: "national-2023-math-sm",
    title: "Examen National 2023 – Mathématiques SM",
    titleAr: "الامتحان الوطني 2023 – الرياضيات SM",
    examYear: 2023,
    subject: "maths",
    filiere: "sm",
    level: "2bac",
    passThreshold: 14,
    totalPoints: 20,
    difficulty: 5,
    flavor: "Complex numbers, integrals, and probability — the 2023 triad of chaos.",
    flavorAr: "الأعداد المركبة، التكامل، والاحتمالات — ثلاثي الفوضى 2023.",
    bgGradient: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    iconEmoji: "π",
    topics: ["nombres complexes", "intégrales", "probabilités", "suites"],
    requirements: [
      { type: "quests_completed", value: 8, label: "Compléter 8 quizzes" },
      { type: "xp_threshold", value: 400, label: "Atteindre 400 XP" },
    ],
    rewards: [
      {
        type: "profile_frame",
        id: "frame-national-2023-math",
        label: "Cadre « Pi Master 2023 »",
        labelAr: "إطار «سيد باي 2023»",
        cssClass: "frame-indigo-glow",
      },
      { type: "baccoins", id: "coins-boss-2023-math", label: "+80 BacCoins", labelAr: "+80 باك كوين" },
    ],
    examPdfUrl: undefined,
    correctionPdfUrl: undefined,
  },

  // ── 2022 National Exams ───────────────────────────────────────────────────
  {
    id: "national-2022-phys-sm",
    title: "Examen National 2022 – Sciences Physiques SM",
    titleAr: "الامتحان الوطني 2022 – العلوم الفيزيائية SM",
    examYear: 2022,
    subject: "physique-chimie",
    filiere: "sm",
    level: "2bac",
    passThreshold: 13,
    totalPoints: 20,
    difficulty: 4,
    flavor: "The class of 2022 survived this. Can you beat their record?",
    flavorAr: "دفعة 2022 اجتازت هذا. هل يمكنك تجاوز رقمهم؟",
    bgGradient: "linear-gradient(135deg, #200122 0%, #6f0000 100%)",
    iconEmoji: "⚛️",
    topics: ["mécanique du solide", "ondes", "noyau atomique", "thermochimie"],
    requirements: [
      { type: "quests_completed", value: 6, label: "Compléter 6 quizzes" },
      { type: "xp_threshold", value: 300, label: "Atteindre 300 XP" },
    ],
    rewards: [
      {
        type: "profile_frame",
        id: "frame-national-2022-sm",
        label: "Cadre « Veteran 2022 »",
        labelAr: "إطار «مخضرم 2022»",
        cssClass: "frame-red-glow",
      },
      { type: "baccoins", id: "coins-boss-2022-sm", label: "+60 BacCoins", labelAr: "+60 باك كوين" },
    ],
    examPdfUrl: undefined,
    correctionPdfUrl: undefined,
  },
  {
    id: "national-2022-math-sm",
    title: "Examen National 2022 – Mathématiques SM",
    titleAr: "الامتحان الوطني 2022 – الرياضيات SM",
    examYear: 2022,
    subject: "maths",
    filiere: "sm",
    level: "2bac",
    passThreshold: 13,
    totalPoints: 20,
    difficulty: 4,
    flavor: "Functions, limits, and 3D geometry conspired to humble thousands. Your turn.",
    flavorAr: "الدوال والحدود والهندسة ثلاثية الأبعاد — دورك الآن.",
    bgGradient: "linear-gradient(135deg, #1f1c2c 0%, #928dab 100%)",
    iconEmoji: "📐",
    topics: ["fonctions", "limites", "géométrie dans l'espace", "dérivées"],
    requirements: [
      { type: "quests_completed", value: 6, label: "Compléter 6 quizzes" },
      { type: "xp_threshold", value: 300, label: "Atteindre 300 XP" },
    ],
    rewards: [
      {
        type: "profile_frame",
        id: "frame-national-2022-math",
        label: "Cadre « Géomètre 2022 »",
        labelAr: "إطار «مهندس 2022»",
        cssClass: "frame-slate-glow",
      },
      { type: "baccoins", id: "coins-boss-2022-math", label: "+60 BacCoins", labelAr: "+60 باك كوين" },
    ],
    examPdfUrl: undefined,
    correctionPdfUrl: undefined,
  },
];
